Repository nhn-on7/marketgg-shop, pull requests merged in 2022-09, with the labels that each got.

#288 관리자 회원 정보 조회 API 개발
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminCsPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminMemberController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/DefaultPageRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/member/AdminAuthResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/member/AdminMemberResponse.java
  src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/member/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/server/service/member/MemberService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/admin/AdminMemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dummy/DummyPageEntity.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberServiceTest.java
Labels: Feat

#290 Feat: Gateway 에서의 호출만 응답하도록 설정
  src/main/java/com/nhnacademy/marketgg/server/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/server/filter/SecurityFilter.java
Labels: Feat

#293 상품 DDL 수정에 따른 Refactoring
  src/main/java/com/nhnacademy/marketgg/server/dto/request/file/ImageCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/product/ProductCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/product/ProductUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/file/ImageResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Image.java
  src/main/java/com/nhnacademy/marketgg/server/repository/image/ImageRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/image/ImageRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/file/DefaultFileService.java
  src/main/java/com/nhnacademy/marketgg/server/service/storage/LocalStorageService.java
  src/main/java/com/nhnacademy/marketgg/server/service/storage/NhnStorageService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/FileControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/admin/AdminProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultFileServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultReviewServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/NhnStorageServiceTest.java
Labels: Refactor

#301 주문 Refactoring
  src/main/java/com/nhnacademy/marketgg/server/constant/MemberBenefits.java
  src/main/java/com/nhnacademy/marketgg/server/constant/PointContent.java
  src/main/java/com/nhnacademy/marketgg/server/controller/payment/PaymentController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/request/PaymentConfirmRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/point/PointHistoryRequest.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/order/OrderCartUpdatedEvent.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/order/OrderCouponUsedEvent.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/order/OrderPointSavedEvent.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/order/OrderProductUpdatedEvent.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/handler/OrderCartUpdatedEventHandler.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/handler/OrderCouponUsedEventHandler.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/handler/OrderPointCanceledEventHandler.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/handler/OrderPointSavedEventHandler.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/handler/OrderProductUpdatedEventHandler.java
  src/main/java/com/nhnacademy/marketgg/server/repository/pointhistory/PointHistoryRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/usedcoupon/UsedCouponRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/usedcoupon/UsedCouponRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/order/DefaultOrderService.java
  src/main/java/com/nhnacademy/marketgg/server/service/order/OrderService.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/PaymentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/TossPaymentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/point/DefaultPointService.java
  src/test/java/com/nhnacademy/marketgg/dummy/Dummy.java
  src/test/java/com/nhnacademy/marketgg/dummy/PaymentDummy.java
  src/test/java/com/nhnacademy/marketgg/server/controller/OrderControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultOrderServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultPointServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/payment/TossPaymentServiceTest.java
Labels: Docs, Refactor, Test

#302 Refactor: Filter 수정
  src/main/java/com/nhnacademy/marketgg/server/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/server/filter/WhiteListFilter.java
Labels: Fix
