Repository nhn-on7/marketgg-shop, pull requests merged in 2022-08, with the labels that each got.

#177 회원 정보 요청시 인증 서버의 회원정보까지 함께 응답 #127
  src/main/java/com/nhnacademy/marketgg/server/aop/AuthInjectAspect.java
  src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/advice/AuthControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/server/dto/AuthInfo.java
  src/main/java/com/nhnacademy/marketgg/server/dto/MemberInfo.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/MemberResponse.java
  src/main/java/com/nhnacademy/marketgg/server/repository/member/MemberRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberService.java
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberServiceTest.java
Labels: Refactor

#168 Feat: 문자열 인코딩 필터 설정
  src/main/java/com/nhnacademy/marketgg/server/config/WebConfig.java
Labels: Feat

#170 Hotfix: Auth AOP 수정
  src/main/java/com/nhnacademy/marketgg/server/aop/AspectUtils.java
  src/main/java/com/nhnacademy/marketgg/server/aop/RoleCheckAspect.java
  src/main/java/com/nhnacademy/marketgg/server/controller/advice/MemberControllerAdvice.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CartControllerTest.java
Labels: Fix

#184 Client -> Shop 검색 옮기기 대작전
  pom.xml
  src/main/java/com/nhnacademy/marketgg/server/config/ElasticConfig.java
  src/main/java/com/nhnacademy/marketgg/server/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/server/controller/AdminPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/CustomerServicePostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/OtoInquiryCommentController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/PostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminCustomerServicePostController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/CommentRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/PostRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/PostResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/PostResponseForDetail.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/SearchRequest.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/SearchRequestBody.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/SearchRequestBodyForBool.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/searchutil/Bool.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/searchutil/BoolQuery.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/searchutil/MultiMatch.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/searchutil/Must.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/searchutil/Query.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/response/SearchBoardResponse.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/response/SearchProductResponse.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/repository/SearchRepository.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/repository/impl/SearchAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/entity/CustomerServicePost.java
  src/main/java/com/nhnacademy/marketgg/server/repository/customerservicecomment/CustomerServiceCommentRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/customerservicecomment/CustomerServiceCommentRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/customerservicepost/CustomerServicePostRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/customerservicepost/CustomerServicePostRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/CustomerServicePostService.java
  src/main/java/com/nhnacademy/marketgg/server/service/OtoInquiryCommentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/SearchService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCustomerServicePostService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultOtoInquiryCommentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultPostService.java
  src/main/java/com/nhnacademy/marketgg/server/utils/KoreanToEnglishTranslator.java
  src/main/java/com/nhnacademy/marketgg/server/utils/subutils/ConvertToEnglishUtil.java
  src/test/java/com/nhnacademy/marketgg/server/controller/AdminCustomerServiceControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/AdminPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CustomerServiceCommentControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CustomerServicePostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/OtoInquiryCommentControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/PostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCustomerServicePostServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultOtoInquiryCommentServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultPostServiceTest.java
Labels: Feat, Fix, Docs, Refactor, Test

#188 MemberInfo 클래스 권한 관리
  src/main/java/com/nhnacademy/marketgg/server/aop/MemberInfoAspect.java
  src/main/java/com/nhnacademy/marketgg/server/dto/MemberInfo.java
Labels: Refactor

#189 Feat: 베스트 후기 쿠폰 지급
  src/main/java/com/nhnacademy/marketgg/server/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/server/constant/CouponsName.java
  src/main/java/com/nhnacademy/marketgg/server/controller/AdminPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/AdminReviewController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminProductController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/coupon/CouponDto.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/SearchRequest.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Label.java
  src/main/java/com/nhnacademy/marketgg/server/entity/OrderDeliveryAddress.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Review.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/GivenCouponEvent.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/SavePointEvent.java
  src/main/java/com/nhnacademy/marketgg/server/event/SignedUpCouponEvent.java
  src/main/java/com/nhnacademy/marketgg/server/service/OtoInquiryCommentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/PointService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultGivenCouponService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultLabelService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultPointService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultReviewService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/AdminReviewControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/GivenCouponRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/ProductRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/UsedCouponRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultPostServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultReviewServiceTest.java
Labels: Feat

#194 클라우드 연동
  pom.xml
  src/main/java/com/nhnacademy/marketgg/server/auth/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/config/ElasticConfig.java
  src/main/java/com/nhnacademy/marketgg/server/controller/StorageController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminProductController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/cloud/Auth.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/cloud/PasswordCredentials.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/cloud/TokenRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/product/ProductCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/DefaultPageResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/ImageResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/cloud/Access.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/cloud/StorageResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/cloud/Tenant.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/cloud/Token.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/cloud/User.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/product/ProductResponse.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/repository/SearchAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Image.java
  src/main/java/com/nhnacademy/marketgg/server/entity/PointHistory.java
  src/main/java/com/nhnacademy/marketgg/server/repository/image/ImageRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/image/ImageRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/ImageService.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/StorageService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultReviewService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/LocalImageService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/NhnStorageService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/StorageImageService.java
  src/main/java/com/nhnacademy/marketgg/server/util/KoreanToEnglishTranslator.java
  src/main/java/com/nhnacademy/marketgg/server/util/subutils/ConvertToEnglishUtil.java
  src/test/java/com/nhnacademy/marketgg/server/ServerApplicationTests.java
  src/test/java/com/nhnacademy/marketgg/server/controller/AdminProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultLabelServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultReviewServiceTest.java
Labels: Feat, Refactor, Test

#202 엘라스틱 서치 동기화로 인한 메소드 수정
  src/main/java/com/nhnacademy/marketgg/server/service/post/DefaultPostService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductService.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultPostServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
Labels: Fix

#204 Validation/Exception 업보청산
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminCategorizationController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminCategoryController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminCsPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminLabelController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminPointController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/customerservice/CommentController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/customerservice/CsPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/member/PointController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/product/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/customerservice/CommentRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/customerservice/PostRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/customerservice/PostStatusUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/label/LabelCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/point/PointHistoryRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/DefaultPageResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/point/PointRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/service/member/DefaultMemberService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/AdminCategorizationControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/AdminCategoryControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/AdminCsPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/AdminLabelControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/AdminPointControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CommentControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CsPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/PointControllerTest.java
Labels: Fix, Refactor

#212 상품 문의 변경 사항
  src/main/java/com/nhnacademy/marketgg/server/auth/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/auth/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminProductInquiryPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/product/ProductInquiryPostController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/info/MemberInfoRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/info/MemberInfoResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/coupon/CouponDto.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/product/ProductInquiryReplyRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/product/ProductInquiryRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/product/ProductInquiryByMemberResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/product/ProductInquiryByProductResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/ProductInquiryPost.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/GivenCouponEvent.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/SavePointEvent.java
  src/main/java/com/nhnacademy/marketgg/server/interceptor/AdminInterceptor.java
  src/main/java/com/nhnacademy/marketgg/server/repository/coupon/CouponRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/deliveryaddress/DeliveryAddressRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/givencoupon/GivenCouponRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/givencoupon/GivenCouponRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/usedcoupon/UsedCouponRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/coupon/CouponService.java
  src/main/java/com/nhnacademy/marketgg/server/service/coupon/GivenCouponService.java
  src/main/java/com/nhnacademy/marketgg/server/service/coupon/UsedCouponService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductInquiryPostService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/ProductInquiryPostService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductInquiryPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/admin/AdminProductInquiryPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductInquiryPostServiceTest.java
Labels: Fix, Style, Refactor

#219 결제 관리 1
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/AccountType.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/AcquireStatus.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/AgencyCode.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/AgencyCodeConverter.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/BankCode.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/CardType.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/CardTypeConverter.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/OwnerType.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/OwnerTypeConverter.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/PaymentMethod.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/PaymentMethodConverter.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/PaymentStatus.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/PaymentType.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/RefundStatus.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/SettlementStatus.java
  src/main/java/com/nhnacademy/marketgg/server/controller/payment/PaymentController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/CardResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/MobilePhonePaymentResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/PaymentCancelResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/PaymentCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/PaymentResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/Receipt.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/TransferPaymentResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/VirtualAccountPaymentResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/request/CardPaymentResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/request/PaymentCancelRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/request/PaymentRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/request/PaymentVerifyRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/request/VirtualAccountPaymentCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Payment.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Transaction.java
  src/main/java/com/nhnacademy/marketgg/server/entity/payment/CardPayment.java
  src/main/java/com/nhnacademy/marketgg/server/entity/payment/MobilePhonePayment.java
  src/main/java/com/nhnacademy/marketgg/server/entity/payment/Payment.java
  src/main/java/com/nhnacademy/marketgg/server/entity/payment/TransferPayment.java
  src/main/java/com/nhnacademy/marketgg/server/entity/payment/VirtualAccountPayment.java
  src/main/java/com/nhnacademy/marketgg/server/repository/payment/CardPaymentRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/payment/MobilePhonePaymentRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/payment/PaymentAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/repository/payment/PaymentRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/payment/PaymentRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/payment/TransferPaymentRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/payment/VirtualAccountPaymentRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/transaction/TransactionRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/transaction/TransactionRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/transaction/TransactionRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/CardPaymentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/MobilePhonePaymentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/PaymentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/TossPaymentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/TransferPaymentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/VirtualAccountPaymentService.java
Labels: Feat

#235 Swagger 프레임워크 적용
  pom.xml
  src/main/java/com/nhnacademy/marketgg/server/config/InterceptorConfig.java
  src/main/java/com/nhnacademy/marketgg/server/config/SwaggerConfig.java
Labels: Feat, Docs, Chore

#245 운송장 번호 추가
  src/main/java/com/nhnacademy/marketgg/server/controller/delivery/DeliveryController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/delivery/CreatedTrackingNoRequest.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Order.java
  src/main/java/com/nhnacademy/marketgg/server/service/delivery/DefaultDeliveryService.java
  src/main/java/com/nhnacademy/marketgg/server/service/delivery/DeliveryService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/delivery/DeliveryControllerTest.java
Labels: Feat, Docs, Test

#234 주문 구현 FINAL
  src/main/java/com/nhnacademy/marketgg/server/constant/PaymentType.java
  src/main/java/com/nhnacademy/marketgg/server/constant/PointContent.java
  src/main/java/com/nhnacademy/marketgg/server/controller/order/OrderController.java
  src/main/java/com/nhnacademy/marketgg/server/delivery/DeliveryAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/dto/ErrorEntity.java
  src/main/java/com/nhnacademy/marketgg/server/dto/PageEntity.java
  src/main/java/com/nhnacademy/marketgg/server/dto/ShopResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/order/CartResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/order/OrderCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/order/OrderInfoRequestDto.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/order/OrderUpdateStatusRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/order/ProductToOrder.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/order/OrderDetailRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/order/OrderFormResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/order/OrderGivenCoupon.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/order/OrderRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/order/OrderToPayment.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Order.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Product.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/OrderCouponCanceledEvent.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/OrderCouponCanceledEventHandler.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/OrderCouponUsedEvent.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/OrderPointCanceledEvent.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/OrderPointCanceledEventHandler.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/OrderPointSavedEvent.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/SavePointEvent.java
  src/main/java/com/nhnacademy/marketgg/server/exception/member/MemberInfoNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/exception/order/OrderMemberNotMatchedException.java
  src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/member/MemberRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/member/MemberRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/pointhistory/PointHistoryRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/pointhistory/PointHistoryRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/pointhistory/PointHistoryRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/usedcoupon/UsedCouponRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/usedcoupon/UsedCouponRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/usedcoupon/UsedCouponRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/order/DefaultOrderService.java
  src/main/java/com/nhnacademy/marketgg/server/service/order/OrderService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductInquiryPostService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/OrderControllerTest.java
Labels: Feat, Docs, Style, Refactor, Test

#246 결제 관리 2
  src/main/java/com/nhnacademy/marketgg/server/aop/AuthInfoAspect.java
  src/main/java/com/nhnacademy/marketgg/server/config/SwaggerConfig.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/BankCode.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/CarrierCode.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/PaymentMethod.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/PaymentMethodConverter.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/PaymentType.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/converter/AccountTypeConverter.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/converter/AgencyCodeConverter.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/converter/BankCodeConverter.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/converter/CardTypeConverter.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/converter/OwnerTypeConverter.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/converter/PaymentStatusConverter.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/converter/PaymentTypeConverter.java
  src/main/java/com/nhnacademy/marketgg/server/constant/payment/converter/SettlementStatusConveter.java
  src/main/java/com/nhnacademy/marketgg/server/controller/advice/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/server/controller/advice/MemberControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/server/controller/cart/CartController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/payment/PaymentController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/ErrorEntity.java
  src/main/java/com/nhnacademy/marketgg/server/dto/ShopResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/PaymentCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/PaymentResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/Receipt.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/request/PaymentConfirmRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/request/PaymentRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/request/VirtualAccountCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/request/VirtualAccountDepositRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/request/VirtualAccountPaymentCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/result/MobilePhonePaymentResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/result/Receipt.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/result/TransferPaymentResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/result/VirtualAccountPaymentResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/common/ErrorEntity.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/order/OrderToPayment.java
  src/main/java/com/nhnacademy/marketgg/server/entity/payment/CardPayment.java
  src/main/java/com/nhnacademy/marketgg/server/entity/payment/MobilePhonePayment.java
  src/main/java/com/nhnacademy/marketgg/server/entity/payment/Payment.java
  src/main/java/com/nhnacademy/marketgg/server/entity/payment/TransferPayment.java
  src/main/java/com/nhnacademy/marketgg/server/entity/payment/VirtualAccountPayment.java
  src/main/java/com/nhnacademy/marketgg/server/repository/payment/PaymentAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/MobilePhonePaymentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/PaymentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/TossPaymentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/TransferPaymentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/VirtualAccountPaymentService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CartControllerTest.java
Labels: Feat, Fix, Docs

#247 쿠폰 Refactoring
  src/main/java/com/nhnacademy/marketgg/server/constant/CouponState.java
  src/main/java/com/nhnacademy/marketgg/server/constant/CouponStatus.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminCouponController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/coupon/UsedCouponController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/coupon/CouponDto.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/coupon/GivenCouponCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/coupon/UsedCouponDto.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/coupon/GivenCouponResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Coupon.java
  src/main/java/com/nhnacademy/marketgg/server/entity/GivenCoupon.java
  src/main/java/com/nhnacademy/marketgg/server/entity/UsedCoupon.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/GivenCouponEvent.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/givencoupon/BestReviewedEvent.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/givencoupon/GiveCouponEvent.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/givencoupon/SignedUpEvent.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/savepoint/NormalReviewedEvent.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/savepoint/PhotoReviewEvent.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/savepoint/RecommendEvent.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/event/savepoint/SavePointEvent.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/handler/GiveCouponHandler.java
  src/main/java/com/nhnacademy/marketgg/server/eventlistener/handler/SavePointHandler.java
  src/main/java/com/nhnacademy/marketgg/server/repository/coupon/CouponRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/pointhistory/PointHistoryRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/pointhistory/PointHistoryRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/coupon/CouponService.java
  src/main/java/com/nhnacademy/marketgg/server/service/coupon/DefaultCouponService.java
  src/main/java/com/nhnacademy/marketgg/server/service/coupon/DefaultGivenCouponService.java
  src/main/java/com/nhnacademy/marketgg/server/service/coupon/DefaultUsedCouponService.java
  src/main/java/com/nhnacademy/marketgg/server/service/coupon/GivenCouponService.java
  src/main/java/com/nhnacademy/marketgg/server/service/coupon/UsedCouponService.java
  src/main/java/com/nhnacademy/marketgg/server/service/member/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/server/service/point/DefaultPointService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultReviewService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/admin/AdminCouponControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCouponServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultGivenCouponServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultReviewServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultUsedCouponServiceTest.java
Labels: Fix, Docs, Refactor

#253 구현 도메인 Swagger 적용
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminCsPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminLabelController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminPointController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminProductController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/customerservice/CommentController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/customerservice/CsPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/member/PointController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/product/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/customerservice/CommentRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/customerservice/PostRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/customerservice/PostStatusUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/label/LabelCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/point/PointHistoryRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/customerservice/CommentResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/customerservice/PostResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/customerservice/PostResponseForDetail.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/label/LabelRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/point/PointRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/product/ProductDetailResponse.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/SearchRequest.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/response/ProductListResponse.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/response/SearchProductResponse.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/repository/ElasticProductRepository.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/repository/SearchAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/repository/SearchRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/ProductService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/admin/AdminLabelControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/LabelRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
Labels: Feat, Docs

#254 주문 TC
  src/main/java/com/nhnacademy/marketgg/server/dto/request/deliveryaddress/DeliveryAddressCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/order/OrderDetailRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Coupon.java
  src/main/java/com/nhnacademy/marketgg/server/exception/coupon/CouponIsAlreadyUsedException.java
  src/main/java/com/nhnacademy/marketgg/server/repository/usedcoupon/UsedCouponRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/order/DefaultOrderService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/OrderControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultOrderServiceTest.java
Labels: Fix, Test

#255 회원가입 로직 변경
  src/main/java/com/nhnacademy/marketgg/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/member/ShopMemberSignUpRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/member/SignupRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/member/SignupResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/DeliveryAddress.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Member.java
  src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/member/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/server/service/member/MemberService.java
Labels: Feat, Refactor

#257 GG 패스 삭제
  src/main/java/com/nhnacademy/marketgg/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Member.java
  src/main/java/com/nhnacademy/marketgg/server/service/member/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/server/service/member/MemberService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberServiceTest.java
Labels: Fix

#262 Refactor: 상품 문의 Entity 수정
  src/main/java/com/nhnacademy/marketgg/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Order.java
  src/main/java/com/nhnacademy/marketgg/server/entity/ProductInquiryPost.java
  src/main/java/com/nhnacademy/marketgg/server/repository/member/MemberRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductInquiryPostService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/ProductInquiryPostService.java
  src/test/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepositoryImplTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductInquiryPostServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultUsedCouponServiceTest.java
Labels: Refactor

#264 Feature/products refactor
  src/main/java/com/nhnacademy/marketgg/server/aop/AuthInfoAspect.java
  src/main/java/com/nhnacademy/marketgg/server/config/InterceptorConfig.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminProductController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminReviewController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/product/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/product/ReviewController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/ErrorEntity.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/DefaultPageRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/product/ProductCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/product/ProductUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/review/ReviewCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/review/ReviewUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultReviewService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/ReviewService.java
  src/main/java/com/nhnacademy/marketgg/server/service/storage/NhnStorageService.java
  src/main/resources/img/lee.png
  src/test/java/com/nhnacademy/marketgg/server/controller/FileControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ReviewControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/admin/AdminProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultFileServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultReviewServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/LocalStorageServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/NhnStorageServiceTest.java
  src/test/resources/lee.png
Labels: Style, Refactor

#261 주문 수정 및 문서 작성
  src/main/java/com/nhnacademy/marketgg/server/constant/OrderStatus.java
  src/main/java/com/nhnacademy/marketgg/server/controller/order/OrderController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/order/CartResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/order/OrderCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/order/OrderInfoRequestDto.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/order/OrderUpdateStatusRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/order/ProductToOrder.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/order/OrderDetailRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/order/OrderRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/orderproduct/OrderProductResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Order.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/OrderCouponCanceledEventHandler.java
  src/main/java/com/nhnacademy/marketgg/server/entity/event/OrderPointCanceledEventHandler.java
  src/main/java/com/nhnacademy/marketgg/server/repository/cart/CartProductRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/cart/CartProductRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/order/OrderRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/order/OrderRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/orderproduct/OrderProductRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/orderproduct/OrderProductRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/order/DefaultOrderService.java
  src/main/java/com/nhnacademy/marketgg/server/service/order/OrderService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/OrderControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultOrderServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultPointServiceTest.java
Labels: Fix, Docs, Style, Test

#260 회원수정, 삭제 리팩토링
  src/main/java/com/nhnacademy/marketgg/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/member/MemberUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/member/MemberWithdrawRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/member/SignupRequest.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Member.java
  src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/member/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/server/service/member/MemberService.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberServiceTest.java
Labels: Refactor

#265 Refactor: 장바구니 로직 수정 #263
  src/main/java/com/nhnacademy/marketgg/server/aop/AuthInfoAspect.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/cart/CartProductResponse.java
  src/main/java/com/nhnacademy/marketgg/server/repository/cart/CartProductRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/image/ImageRepositoryImpl.java
  src/test/java/com/nhnacademy/marketgg/server/repository/cart/CartProductRepositoryTest.java
Labels: Refactor

#267 주문 UI 와 함께하는 수정
  src/main/java/com/nhnacademy/marketgg/server/controller/order/OrderController.java
  src/main/java/com/nhnacademy/marketgg/server/repository/order/OrderRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/order/OrderRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/order/DefaultOrderService.java
  src/main/java/com/nhnacademy/marketgg/server/service/order/OrderService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/OrderControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultOrderServiceTest.java
Labels: Fix

#273 결제 테스트 코드 작성
  src/main/java/com/nhnacademy/marketgg/server/aop/AuthInfoAspect.java
  src/main/java/com/nhnacademy/marketgg/server/controller/payment/PaymentController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/ErrorEntity.java
  src/main/java/com/nhnacademy/marketgg/server/dto/payment/PaymentResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/order/OrderToPayment.java
  src/main/java/com/nhnacademy/marketgg/server/repository/payment/PaymentAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/PaymentService.java
  src/main/java/com/nhnacademy/marketgg/server/service/payment/TossPaymentService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/payment/PaymentControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dummy/PaymentDummy.java
  src/test/java/com/nhnacademy/marketgg/server/service/payment/TossPaymentServiceTest.java
Labels: Fix, Docs, Refactor, Test

#276 Refactor: 배송지 관리 최종본
  src/main/java/com/nhnacademy/marketgg/server/controller/member/DeliveryAddressController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/deliveryaddress/DeliveryAddressCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/deliveryaddress/DeliveryAddressResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/DeliveryAddress.java
  src/main/java/com/nhnacademy/marketgg/server/exception/deliveryaddresses/MinimumDeliveryAddressCountException.java
  src/main/java/com/nhnacademy/marketgg/server/repository/deliveryaddress/DeliveryAddressRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/deliveryaddress/DefaultDeliveryAddressService.java
  src/main/java/com/nhnacademy/marketgg/server/service/deliveryaddress/DeliveryAddressService.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultDeliveryAddressServiceTest.java
Labels: Feat, Refactor

#277 Feature/products
  src/main/java/com/nhnacademy/marketgg/server/controller/product/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/product/ReviewController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/product/ProductDetailResponse.java
  src/main/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/ProductService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ReviewControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryImplTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
Labels: Feat, Refactor

#279 트랜잭션 설정
  src/main/java/com/nhnacademy/marketgg/server/service/cart/DefaultCartProductService.java
Labels: Fix

#282 상품 검색 버그 수정
  src/main/java/com/nhnacademy/marketgg/server/controller/product/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/dto/request/SearchRequestBodyForBool.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/repository/SearchAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductService.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
Labels: Fix, Test

#281 Refactor/client fix
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminCouponController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/admin/AdminProductInquiryPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/product/ProductInquiryPostController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/product/ProductInquiryReplyRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/product/ProductInquiryResponse.java
  src/main/java/com/nhnacademy/marketgg/server/repository/coupon/CouponRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/coupon/DefaultGivenCouponService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/DefaultProductInquiryPostService.java
  src/main/java/com/nhnacademy/marketgg/server/service/product/ProductInquiryPostService.java
Labels: Fix, Style, Refactor

#285 주문 프로세스 연동
  src/main/java/com/nhnacademy/marketgg/server/controller/order/OrderController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/order/CartOrderRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/order/ProductToOrder.java
  src/main/java/com/nhnacademy/marketgg/server/repository/cart/CartProductRepositoryImpl.java
  src/test/java/com/nhnacademy/marketgg/server/controller/OrderControllerTest.java
Labels: Fix, Style

#286 회원 수정, 탈퇴 최종본
  src/main/java/com/nhnacademy/marketgg/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/member/MemberWithdrawRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/TokenResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/auth/UuidTokenResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Member.java
  src/main/java/com/nhnacademy/marketgg/server/exception/auth/AuthServerResponseException.java
  src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthAdapter.java
  src/main/java/com/nhnacademy/marketgg/server/repository/auth/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/member/DefaultMemberService.java
  src/main/java/com/nhnacademy/marketgg/server/service/member/MemberService.java
Labels: Feat, Refactor
