Repository nhn-on7/marketgg-shop, pull requests merged in 2022-07, with the labels that each got.

#27 Feature/category update
  src/main/java/com/nhnacademy/marketgg/server/config/WebConfiguration.java
  src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/CategoryRequest.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
  src/main/java/com/nhnacademy/marketgg/server/service/CategoryService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CategoryControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dto/CategoryRequest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryServiceTest.java
Labels: Feat, Test

#30 Feature/category delete
  src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
  src/main/java/com/nhnacademy/marketgg/server/service/CategoryService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CategoryControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryServiceTest.java
Labels: Feat, Test

#37 Test: 상품 등록 컨트롤러 테스트 #22
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/repository/ProductRepository.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/ProductRepositoryTest.java
Labels: Test

#36 Feature/category retrieve
  src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/CategoryResponse.java
  src/main/java/com/nhnacademy/marketgg/server/repository/CategoryRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/CategoryService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CategoryControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryServiceTest.java
Labels: Feat, Test

#41 Feature/product retrieve
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/ProductResponse.java
  src/main/java/com/nhnacademy/marketgg/server/repository/ProductRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/ProductRepositoryTest.java
Labels: Feat, Test

#42 Feat: 상품 삭제 기능 구현 #12
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/main/resources/application.properties
Labels: Feat

#47 Test/product controller test
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/ProductRepositoryTest.java
Labels: Test

#48 상품 엔티티 속성 수정 및 controller, test 코드 수정
  productRequest.http
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/ProductResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Product.java
  src/main/java/com/nhnacademy/marketgg/server/exception/AssetNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/repository/AssetRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/CategoryRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/ProductRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
Labels: Style, Test

#50 카테고리 생성 구현/테스트 코드 PR
  src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/CategoryCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/CategoryRequest.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Categorization.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
  src/main/java/com/nhnacademy/marketgg/server/exception/CategorizationNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/service/CategoryService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CategoryControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryServiceTest.java
Labels: Feat, Style, Test

#51 카테고리 수정 구현/테스트 코드 PR
  src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/CategoryUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
  src/main/java/com/nhnacademy/marketgg/server/service/CategoryService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CategoryControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryServiceTest.java
Labels: Feat, Style, Test

#56 Feature/product asset
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Asset.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Image.java
  src/main/java/com/nhnacademy/marketgg/server/repository/ImageRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/AssetService.java
  src/main/java/com/nhnacademy/marketgg/server/service/ImageService.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultAssetService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
Labels: Feat

#39 라벨 기능 PR
  src/main/java/com/nhnacademy/marketgg/server/controller/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/server/controller/LabelController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/LabelCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/LabelRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Label.java
  src/main/java/com/nhnacademy/marketgg/server/exception/LabelNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/repository/LabelRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/LabelService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultLabelService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/LabelControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dto/LabelCreateRequest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultLabelServiceTest.java
Labels: Feat, Fix, Test

#61 Chore: .yml 포트번호 7080으로 변경
  src/main/resources/application.yml
Labels: Chore

#65 Fix: 상품 컨트롤러 맵핑 수정
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
Labels: Fix

#68 Feat: 상품 검색 기능 구현 #13
  productRequest.http
  readme/products.md
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/httprequest/productRequest.http
  src/main/java/com/nhnacademy/marketgg/server/repository/ProductRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
Labels: Feat

#73 상품 등록 service, controller 레이어 테스트 구현
  pom.xml
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultLabelServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
  src/test/resources/application.yml
  test.png
Labels: Test

#76 Feature/products test code 작성
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
Labels: Test

#80 Feat: 카테고리 코드로 상품 검색기능 구현 #79
  readme/products.md
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/httprequest/productRequest.http
  src/main/java/com/nhnacademy/marketgg/server/repository/ProductRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
Labels: Feat

#81 Fix: 맵핑 변경
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
Labels: Feat

#83 Docs: 상품 Java Docs 추가 #82
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Asset.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Image.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Product.java
  src/main/java/com/nhnacademy/marketgg/server/repository/ProductRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
Labels: Docs

#84 찜 관리 완료
  pom.xml
  src/main/java/com/nhnacademy/marketgg/server/controller/DibController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/DibCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/DibDeleteRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/DibRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Dib.java
  src/main/java/com/nhnacademy/marketgg/server/exception/DibNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/exception/MemberNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/exception/ProductNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/repository/DibRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/dib/DibRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/dib/DibRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/dib/DibRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/DibService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultDibService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/DibControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dto/request/MemberCreateRequest.java
  src/test/java/com/nhnacademy/marketgg/server/dto/request/MemberGradeCreateRequest.java
  src/test/java/com/nhnacademy/marketgg/server/entity/Member.java
  src/test/java/com/nhnacademy/marketgg/server/entity/MemberGrade.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultDibServiceTest.java
Labels: Feat, Docs, Test

#87 Feature/products inquiry
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductInquiryPostController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductInquiryReply.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductInquiryRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/ProductInquiryResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/ProductResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Member.java
  src/main/java/com/nhnacademy/marketgg/server/entity/MemberGrade.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Product.java
  src/main/java/com/nhnacademy/marketgg/server/entity/ProductInquiryPost.java
  src/main/java/com/nhnacademy/marketgg/server/httprequest/prodcutInquiryPostRequest.http
  src/main/java/com/nhnacademy/marketgg/server/repository/ProductInquiryPostRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductInquiryPostService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductInquiryPostService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/main/resources/application.yml
Labels: Feat

#85 상품관리 리뷰 후 승인 부탁드립니다.
  pom.xml
  productRequest.http
  readme/products.md
  src/main/java/com/nhnacademy/marketgg/server/controller/DibController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductInquiryPostController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/DibCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/DibDeleteRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductInquiryReply.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductInquiryRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/ProductUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/DibRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/ProductInquiryResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/ProductResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Asset.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Categorization.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Dib.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Image.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Product.java
  src/main/java/com/nhnacademy/marketgg/server/entity/ProductInquiryPost.java
  src/main/java/com/nhnacademy/marketgg/server/exception/DibNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/exception/MemberNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/exception/ProductNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/exception/product/ProductNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/httprequest/prodcutInquiryPostRequest.http
  src/main/java/com/nhnacademy/marketgg/server/httprequest/productRequest.http
  src/main/java/com/nhnacademy/marketgg/server/repository/DibRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/ProductInquiryPostRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/ProductRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/dib/DibRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/dib/DibRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/dib/DibRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/DibService.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductInquiryPostService.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultDibService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductInquiryPostService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/marketgg/server/controller/DibControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/dto/request/MemberCreateRequest.java
  src/test/java/com/nhnacademy/marketgg/server/dto/request/MemberGradeCreateRequest.java
  src/test/java/com/nhnacademy/marketgg/server/entity/Member.java
  src/test/java/com/nhnacademy/marketgg/server/entity/MemberGrade.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultDibServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultLabelServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
  test.png
Labels: Feat, Fix, Docs, Test

#78 카테고리 관련 URI 매핑 수정
  src/main/java/com/nhnacademy/marketgg/server/controller/CategorizationController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/LabelController.java
Labels: Fix, Style

#75 JavaDocs 작성 및 GG PASS 코드 수정
  src/main/java/com/nhnacademy/marketgg/server/controller/CategorizationController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/server/controller/LabelController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Categorization.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Label.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Member.java
  src/main/java/com/nhnacademy/marketgg/server/exception/categorization/CategorizationNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/exception/category/CategoryNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/exception/label/LabelNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/exception/member/MemberNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/exception/membergrade/MemberGradeNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/service/CategorizationService.java
  src/main/java/com/nhnacademy/marketgg/server/service/CategoryService.java
  src/main/java/com/nhnacademy/marketgg/server/service/LabelService.java
  src/main/java/com/nhnacademy/marketgg/server/service/MemberService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultLabelService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberServiceTest.java
Labels: Fix, Docs

#90 Style: 코딩 컨벤션대로 수정
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
Labels: Style

#108 Docs: 누락된 찜 JavaDoc 작성 #107
  src/main/java/com/nhnacademy/marketgg/server/controller/AdminProductInquiryPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/CategorizationController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/DibController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/LabelController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductAdminController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductInquiryPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductMemberController.java
  src/main/java/com/nhnacademy/marketgg/server/service/DibService.java
Labels: Docs

#111 카테고리 Validation 적용
  pom.xml
  src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/CategorizationCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/CategoryCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/CategoryUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/CategorizationRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/CategoryRetrieveResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Categorization.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Category.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CategoryControllerTest.java
Labels: Feat

#113 Feature/repository tc
  src/main/java/com/nhnacademy/marketgg/server/dto/request/LabelCreateRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/MemberCreateRequest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/CategorizationRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/CategoryRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/DibRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/LabelRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultDibServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultLabelServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberServiceTest.java
Labels: Test

#117 상품관리 페이지네이션
  src/main/java/com/nhnacademy/marketgg/server/controller/AdminProductInquiryPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductAdminController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductMemberController.java
  src/main/java/com/nhnacademy/marketgg/server/httprequest/productRequest.http
  src/main/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductAdminControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductMemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryImplTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
Labels: Feat, Refactor

#119 Feature/ 상품 문의 조회 Pagination 구현 #86
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductInquiryPostController.java
  src/main/java/com/nhnacademy/marketgg/server/httprequest/prodcutInquiryPostRequest.http
  src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/productinquirypost/ProductInquiryPostRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductInquiryPostService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductInquiryPostService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductInquiryPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductInquiryPostServiceTest.java
Labels: Feat

#103 Shop API 서버에서 사용자 접근 권한 체크
  pom.xml
  src/main/java/com/nhnacademy/marketgg/server/aop/RoleCheckAspect.java
  src/main/java/com/nhnacademy/marketgg/server/aop/annotation/Role.java
  src/main/java/com/nhnacademy/marketgg/server/aop/annotation/RoleCheck.java
  src/main/java/com/nhnacademy/marketgg/server/controller/AuthControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductAdminController.java
  src/main/java/com/nhnacademy/marketgg/server/exception/auth/UnAuthenticException.java
  src/main/java/com/nhnacademy/marketgg/server/exception/auth/UnAuthorizationException.java
  src/main/resources/application.yml
Labels: Feat

#120 Shop ES(Elastic Search) Server 연동
  pom.xml
  src/main/java/com/nhnacademy/marketgg/server/ServerApplication.java
  src/main/java/com/nhnacademy/marketgg/server/config/ElasticSearchConfig.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductMemberController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/EsProductSearchRequest.java
  src/main/java/com/nhnacademy/marketgg/server/elasticrepository/EsProductRepository.java
  src/main/java/com/nhnacademy/marketgg/server/elasticrepository/EsRepositoryMarker.java
  src/main/java/com/nhnacademy/marketgg/server/entity/elastic/EsProduct.java
  src/main/java/com/nhnacademy/marketgg/server/repository/JpaRepositoryMarker.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/main/resources/application.yml
Labels: Feat, Fix, Docs

#124 Feat: 회원가입
  src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/ShopMemberSignUpRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/ShopMemberSignUpResponse.java
  src/main/java/com/nhnacademy/marketgg/server/entity/DeliveryAddress.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Member.java
  src/main/java/com/nhnacademy/marketgg/server/repository/member/MemberRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/MemberService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberService.java
Labels: Feat, Docs, Refactor

#128 회원 정보 API 개발
  src/main/java/com/nhnacademy/marketgg/server/annotation/Auth.java
  src/main/java/com/nhnacademy/marketgg/server/annotation/RoleCheck.java
  src/main/java/com/nhnacademy/marketgg/server/aop/AuthInjectAspect.java
  src/main/java/com/nhnacademy/marketgg/server/aop/RoleCheckAspect.java
  src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/advice/GlobalControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/server/controller/advice/MemberControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/MemberResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/common/CommonResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/common/ErrorEntity.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/common/ListResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/common/SingleResponse.java
  src/main/java/com/nhnacademy/marketgg/server/exception/auth/UnAuthorizationException.java
  src/main/java/com/nhnacademy/marketgg/server/repository/member/MemberRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/MemberService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberServiceTest.java
Labels: Feat

#133 Fix: Import 이슈 해결
  src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/service/MemberService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
Labels: Fix

#134 Feat: 회원탈퇴
  src/main/java/com/nhnacademy/marketgg/server/annotation/UUID.java
  src/main/java/com/nhnacademy/marketgg/server/aop/AspectUtils.java
  src/main/java/com/nhnacademy/marketgg/server/aop/UuidAspect.java
  src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/MemberWithdrawRequest.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Member.java
  src/main/java/com/nhnacademy/marketgg/server/service/MemberService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberService.java
Labels: Refactor

#143 [ES] 서버 설정 및 상품, 게시판 Repository 생성 PR
  pom.xml
  src/main/java/com/nhnacademy/marketgg/server/ServerApplication.java
  src/main/java/com/nhnacademy/marketgg/server/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/document/ElasticBoard.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/document/ElasticProduct.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/repository/ElasticBoardRepository.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/repository/ElasticProductRepository.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/repository/ElasticRepositoryMarker.java
  src/main/java/com/nhnacademy/marketgg/server/repository/dib/DibRepository.java
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/marketgg/server/controller/AdminProductInquiryPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/CategorizationRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/CategoryRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/DibRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/LabelRepositoryTest.java
Labels: Feat, Chore

#144 상품관리 공통 응답객체 및 페이지네이션 적용, 테스트코드 정상화
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductAdminController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/request/DefaultPageRequest.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/DefaultPageResult.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/temp/CommonResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/temp/PageListResponse.java
  src/main/java/com/nhnacademy/marketgg/server/dto/response/temp/README.md
  src/main/java/com/nhnacademy/marketgg/server/httprequest/productRequest.http
  src/main/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductAdminControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/repository/product/ProductRepositoryImplTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
Labels: Fix, Refactor

#158 URL Rewriting 적용 및 프로파일 설정 개선
  pom.xml
  src/main/java/com/nhnacademy/marketgg/server/aop/AuthInjectAspect.java
  src/main/java/com/nhnacademy/marketgg/server/controller/AdminPointController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/AdminProductInquiryPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/CategorizationController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/CategoryController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/CouponController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/DibController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/LabelController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/PointController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductAdminController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductInquiryPostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/UsedCouponController.java
  src/main/java/com/nhnacademy/marketgg/server/httprequest/couponRequest.http
  src/main/java/com/nhnacademy/marketgg/server/httprequest/givenCouponRequest.http
  src/main/java/com/nhnacademy/marketgg/server/httprequest/prodcutInquiryPostRequest.http
  src/main/java/com/nhnacademy/marketgg/server/httprequest/productRequest.http
  src/main/java/com/nhnacademy/marketgg/server/httprequest/usedCouponRequest.http
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/marketgg/server/controller/AdminPointControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/AdminProductInquiryPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CategorizationControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CategoryControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/CouponControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/DibControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/LabelControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/MemberControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/PointControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductAdminControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductInquiryPostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/UsedCouponControllerTest.java
  src/test/resources/application.yml
Labels: Feat, Style, Chore

#159 UUID 대신 멤버 정보 주입
  src/main/java/com/nhnacademy/marketgg/server/aop/AuthInjectAspect.java
  src/main/java/com/nhnacademy/marketgg/server/aop/MemberInfoAspect.java
  src/main/java/com/nhnacademy/marketgg/server/controller/MemberController.java
  src/main/java/com/nhnacademy/marketgg/server/dto/MemberInfo.java
  src/main/java/com/nhnacademy/marketgg/server/repository/member/MemberRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/member/MemberRepositoryImpl.java
Labels: Feat

#165 크라우드 펀딩 연관 모두 삭제
  src/main/java/com/nhnacademy/marketgg/server/entity/Crowdfunding.java
  src/main/java/com/nhnacademy/marketgg/server/entity/FundingProduct.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Order.java
  src/main/java/com/nhnacademy/marketgg/server/exception/crowdfunding/CrowdfundingNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/exception/fundingproduct/FundingProductNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/server/repository/crowdfunding/CrowdfundingRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/crowdfunding/CrowdfundingRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/crowdfunding/CrowdfundingRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/server/repository/fundingproduct/FundingProductRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/fundingproduct/FundingProductRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/server/repository/fundingproduct/FundingProductRepositoryImpl.java
  src/test/java/com/nhnacademy/marketgg/server/controller/PointControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultPointServiceTest.java
Labels: Fix

#166 ES 상품, 게시판 CRUD 작성
  src/main/java/com/nhnacademy/marketgg/server/config/DbConfig.java
  src/main/java/com/nhnacademy/marketgg/server/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/server/controller/CustomerServicePostController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductAdminController.java
  src/main/java/com/nhnacademy/marketgg/server/controller/ProductController.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/document/ElasticBoard.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/document/ElasticProduct.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/repository/ElasticBoardRepository.java
  src/main/java/com/nhnacademy/marketgg/server/elastic/repository/ElasticProductRepository.java
  src/main/java/com/nhnacademy/marketgg/server/entity/Cart.java
  src/main/java/com/nhnacademy/marketgg/server/entity/CustomerServiceComment.java
  src/main/java/com/nhnacademy/marketgg/server/entity/CustomerServicePost.java
  src/main/java/com/nhnacademy/marketgg/server/repository/asset/AssetRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/customerservicepost/CustomerServicePostRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/image/ImageRepository.java
  src/main/java/com/nhnacademy/marketgg/server/repository/product/ProductRepository.java
  src/main/java/com/nhnacademy/marketgg/server/service/ProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultAssetService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCartProductService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultCustomerServicePostService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultLabelService.java
  src/main/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductService.java
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/marketgg/server/controller/CustomerServicePostControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductAdminControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/controller/ProductControllerTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategorizationServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultCategoryServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultLabelServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultMemberServiceTest.java
  src/test/java/com/nhnacademy/marketgg/server/service/impl/DefaultProductServiceTest.java
Labels: Feat, Fix, Style, Test
